---
- name: ssh authorize public key
  become: yes
  become_user: "{{ troy_user_name }}"
  authorized_key:
    user: "{{ troy_user_name }}"
    state: present
    key: "{{ lookup('file', '.ssh/id_rsa.pub') }}"

- name: add user to sudoers
  become: yes
  template:
    src: sudo.conf.j2
    dest: /etc/sudoers.d/{{ troy_user_name }}

- name: clone dotfiles repo
  become: yes
  become_user: "{{ troy_user_name }}"
  git:
    repo: "{{ troy_dotfiles_repo }}"
    dest: /home/{{ troy_user_name }}/.dotfiles
    accept_hostkey: yes
    key_file: "{{ troy_private_key_path }}"
    force: yes

- name: install dotfiles
  become: yes
  become_user: "{{ troy_user_name }}"
  shell: ./bootstrap.sh
  args:
    chdir: /home/{{ troy_user_name }}/.dotfiles
    creates: /home/{{ troy_user_name }}/.config/fish/config.fish
