---
- name: create group
  become: yes
  group:
    name: "{{ troy_user_name }}"
    state: present
    gid: "{{ troy_group_id }}"

- name: create user
  become: yes
  user:
    state: present
    name: "{{ troy_user_name }}"
    uid: "{{ troy_user_id }}"
    group: users
    groups: "{{ troy_user_name }},sudo,staff"
    comment: Troy Kinsella
    shell: /usr/bin/fish

- name: create home
  become: yes
  file:
    path: /home/{{ troy_user_name }}
    owner: "{{ troy_user_name }}"
    group: "{{ troy_user_name }}"
    recurse: yes
